#!/bin/bash

if [ ${DIB_DEBUG_TRACE:-0} -gt 0 ]; then
    set -x
fi
set -eu
set -o pipefail

# Adapted from: https://github.com/apache/incubator-mxnet/blob/0.11.0.rc3/setup-utils/install-mxnet-ubuntu-python.sh

# Clone MXNET repository
git clone https://github.com/apache/incubator-mxnet.git $HOME/mxnet/ --recursive

MXNET_HOME="$HOME/mxnet/"
echo "MXNet root folder: $MXNET_HOME"

echo "Installing build-essential, libatlas-base-dev, libopencv-dev, pip, graphviz ..."
sudo apt-get update
#libopencv-dev installed already in script-05, redundant.
sudo apt-get install -y build-essential libatlas-base-dev libopencv-dev graphviz

echo "Building MXNet core. This can take few minutes..."
cd "$MXNET_HOME"
make -j$(nproc)

echo "Installing Numpy..."
sudo apt-get install python-numpy

echo "Installing Python setuptools pip..."
sudo apt-get install -y python-setuptools python-pip

echo "Updating pip..."
sudo pip install -U pip

echo "Installing Python package for MXNet..."
cd python; sudo python setup.py install

echo "Adding MXNet path to your ~/.bashrc file"
echo "export PYTHONPATH=$MXNET_HOME/python:$PYTHONPATH" >> ~/.bashrc
source ~/.bashrc

echo "Install Graphviz for plotting MXNet network graph..."
sudo pip install graphviz

echo "Installing Jupyter notebook..."
sudo pip install jupyter

echo "Done! MXNet for Python installation is complete. Go ahead and explore MXNet with Python :-)"
